apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managerdash-ingress
  namespace: "2401032"
  labels:
    app: managerdash
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: managerdash-2401032.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: managerdash-service
            port:
              number: 80
