apiVersion: v1
kind: Service
metadata:
  name: managerdash-service
  namespace: 2401032
  labels:
    app: managerdash
spec:
  type: ClusterIP
  selector:
    app: managerdash
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
